#-------------------------------
# General Site Settings

title: The Equipment Company
description: Quality, Service & Value you can trust
email: info@tec.net.pk

# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: About, url: '#about'}
- {name: Products & Services, url: '#products'}
- {name: Clients, url: '#clients'}
- {name: Contact, url: '#contact'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'THE EQUIPMENT COMPANY is the leading Distribution Company for Engineering
Laboratory equipment and the only large company that is focused on this Market
Segment.'
  rel-author: ''
  rel-publisher: ''

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X

#-------------------------------
# About Section

# NOTE: The avatar is defined in the all.sass document.

blurb: >
  THE EQUIPMENT COMPANY is a young and dedicated company for Educational Products, came into being on the January 2012. THE EQUIPMENT COMPANY employs an experienced and exceedingly competent team of sales personnel committed to accomplish the needs if its customers and back up its sales with prompt after sales/services by trained service engineers.Visionary thinking, quality management and the competence of our staff are the backbone of our business and the basis for its strategic alignment. We are consistently taking up the challenges and demands with regard to product quality, safety and flexibility, thus ensuring our customers and us a leading position in the market.
  THE EQUIPMENT COMPANY is the leading Distribution Company for Engineering Laboratory equipment and the only large company that is focused on this Market Segment. We are a value added solutions supplier. We take full responsibility for Marketing, Sales and Service and limit our principal’s time and expense support. The company is proud to be one stop supplier for all laboratory needs. We engage with our customers from inception during the construction phase with laboratory furniture and
  continue the relationship during the equipment procurement, maintenance and ongoing service and support phases.
#-------------------------------
# Work Section

projects:
- {name: TYPO International Design Talks, folder: 'proj-1', file: 'work/proj-1.html'}
- {name: City-IN website concept, folder: 'proj-2', file: 'work/proj-2.html'}
- {name: Crispy Icons, folder: 'proj-3', file: 'work/proj-3.html'}
- {name: Flat Mobile UI/UX Concept, folder: 'proj-4', file: 'work/proj-4.html'}
- {name: Fresh It Up, folder: 'proj-5', file: 'work/proj-5.html'}
- {name: Timeline Page, folder: 'proj-6', file: 'work/proj-6.html'}
- {name: Weather Dashboard, folder: 'proj-7', file: 'work/proj-7.html'}
- {name: Stripes & Co, folder: 'proj-8', file: 'work/proj-8.html'}




#-------------------------------
# Clients Section

clients:
- {avatar: 'face-aaroni.jpg',
  name: 'Scott Summers',
  title: 'Director of Design, OnToText Ind.',
  quote: '<p><strong>While we all felt that Travis was a great</strong> asset to our team — and really worked hard to understand our products from the point of view of the customer — we also all agree he should shower more often.</p>',
  logo: 'logo1.png'}
- {avatar: 'face-atariboy.jpg',
  name: 'Hank McCoy',
  title: 'Eater of Salad, Antartica Int.',
  quote: '<p><strong>Working with Travis was the highlight of my career.</strong> Other moments of note were collecting the largest number of paperclips in the office, and winning a trophy for saying "uh huh, and then what?" 30 times in a row to my girlfriend without her noticing.</p>',
  logo: 'logo2.png'}
- {avatar: 'face-jackiesaik.jpg',
  name: 'Stacy Lang',
  title: 'Social Media Girl, Quebec Int.',
  quote: '<p><strong>Yea, I guess hes good at computers or something,</strong> but let me ask you this: If a cat always lands on its feet, and buttered bread always lands butter side down, what would happen if you tied buttered bread on top of a cat?</p>',
  logo: 'logo3.png'}
- {avatar: 'face-teleject.jpg',
  name: 'Cleatus Cassidy',
  title: 'VP of Helmut, Lorem Sorem LLC.',
  quote: '<p><strong>Back in old country</strong> only nerds who is playing on computers. Now all bros is wanting to make codes and junk. I lost foot in war. You dont see girls asking me about homework.</p>',
  logo: 'logo4.png'}


#-------------------------------
# Contact Section

social:
- {icon: 'twitter', link: 'http://twitter.com/devtipsshow'}
- {icon: 'dribbble', link: 'https://dribbble.com/travisneilson'}
- {icon: 'behance', link: 'https://www.behance.net/travisneilson'}
- {icon: 'youtube', link: 'https://www.youtube.com/DevTipsForDesigners'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/travisneilson/'}


# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
